version: "3.9"

services:
  nginx:
    image: jumasta/nginx:no-cert
    ports:
      - "80:80"    
  frontend:
    image: jumasta/frontend:1.0
    env_file:
      - frontend.env
  api:
    image: jumasta/api:1.0
